version: '1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  server:
    build: .
    ports:
      - 4000:4000
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis-server:
        condition: service_healthy
    # image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow access to Docker daemon
      - ./utils/temp:/app/utils/temp
    privileged: true
    