version: '1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis-server:
    image: redis
    ports:
      - 6379:6379

  server:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - redis-server
      - python
      - java
      - javascript
      - cpp

  python:
    image: python:3.10-alpine
    entrypoint: ["tail", "-f", "/dev/null"]

  javascript:
    image: node:18-alpine
    entrypoint: ["tail", "-f", "/dev/null"]

  java:
    image: openjdk:17-alpine
    entrypoint: ["tail", "-f", "/dev/null"]

  cpp:
    image: gcc
    entrypoint: ["tail", "-f", "/dev/null"]
